<?php
    /**
     * @var Type_6 $tab
     */
?>
<div class="accordion-mixed__content-inner">
    <div class="video-tab-row">
        <style>
            .video-tab-row .video-tab-col:last-child {
                padding-bottom: 0;
            }
        </style>
        <?php

            $videos = (array) $tab->getVideos();
            $mod = ((count($videos) > 3 or (count($videos) === 2)) and count($videos) % 2 === 0) ? 'video-tab-col_full-width' : '';
            foreach ($videos as $index => $video) :
                $video_file = !empty($video['video_file']) ? $video['video_file'] : '';
                $video_url = !empty($video['video']) ? esc_url_raw(trim((string) $video['video'])) : '';
                $video_host = $video_url ? strtolower((string) wp_parse_url($video_url, PHP_URL_HOST)) : '';
                $video_is_instagram = in_array($video_host, array('instagram.com', 'www.instagram.com'), true);
                $video_embed = $video_url ? wp_oembed_get($video_url) : '';

                if (!$video_embed && $video_url && function_exists('mastak_get_instagram_oembed')) {
                    $video_embed = mastak_get_instagram_oembed($video_url);
                }

                // Some hosting providers block WordPress's request to the YouTube oEmbed API.
                // Build a safe player URL as a fallback for regular and short YouTube links.
                if (!$video_embed && $video_url) {
                    $video_parts = wp_parse_url($video_url);
                    $youtube_host = !empty($video_parts['host']) ? strtolower($video_parts['host']) : '';
                    $video_id = '';

                    if (in_array($youtube_host, array('youtu.be', 'www.youtu.be'), true)) {
                        $video_id = trim($video_parts['path'] ?? '', '/');
                    } elseif (in_array($youtube_host, array('youtube.com', 'www.youtube.com', 'm.youtube.com'), true)) {
                        parse_str($video_parts['query'] ?? '', $video_query);
                        $video_id = $video_query['v'] ?? '';
                    }

                    if (preg_match('/^[A-Za-z0-9_-]{11}$/', $video_id)) {
                        $video_embed = sprintf(
                            '<iframe src="https://www.youtube-nocookie.com/embed/%s" title="YouTube video player" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
                            esc_attr($video_id)
                        );
                    }
                }
                $desktop_width = !empty($video['desktop_width']) ? (int) $video['desktop_width'] : 100;
                $desktop_width = min(100, max(1, $desktop_width));
                $wrapper_id = 'vide-' . $tab->getId() . '-' . $index;
                ?>
                <div class="video-tab-col <?= (count($videos) === $index + 1) ? $mod : ''; ?>">
                    <style>
                        #<?= esc_attr($wrapper_id); ?> {
                            width: 100%;
                            margin-left: auto;
                            margin-right: auto;
                        }

                        @media (min-width: 768px) {
                            #<?= esc_attr($wrapper_id); ?> {
                                max-width: <?= $desktop_width; ?>%;
                            }
                        }
                    </style>
                    <div id="<?= esc_attr($wrapper_id); ?>" class="video-tab-wrapper<?= $video_file ? ' video-tab-wrapper--file' : ''; ?><?= $video_is_instagram ? ' video-tab-wrapper--instagram' : ''; ?>"<?= ($video_file || $video_is_instagram) ? ' style="padding-top:0;"' : ''; ?>>
                        <?php if ($video_file) : ?>
                            <video controls preload="metadata" style="display:block;width:100%;height:auto;">
                                <source src="<?= esc_url($video_file); ?>" type="video/mp4">
                                Ваш браузер не поддерживает воспроизведение видео.
                            </video>
                        <?php elseif ($video_embed) : ?>
                            <?php // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress oEmbed or from a validated YouTube ID. ?>
                            <?= $video_embed; ?>
                        <?php elseif ($video_url) : ?>
                            <a href="<?= esc_url($video_url); ?>" target="_blank" rel="noopener noreferrer">
                                Смотреть видео
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
    </div>
</div>
